### PR TITLE
Add configuration for the check-in endpoint

### PR DESCRIPTION
**Pull request by enolfc**
# Summary

---

**Related issue :**

### CODE REVIEW

**Comment by enolfc** [comment]
Needed for https://github.com/EGI-Federation/fedcloud-catchall-operations/pull/209

**Review by CatalinCondurache — APPROVED** [review]
good to go

**Review by CatalinCondurache — APPROVED** [review]
good to go

**Review by CatalinCondurache — APPROVED** [review]
good to go

**Pull request merged**
